feat: infer library type if seq_ids don't match
zavolanlab/htsinfer pull request #129
Opened 2023-05-24 11:38 UTC by BorisYourich

### Description

I have added a GetOrientation class instance in the GetLibType class so that when
the sequence identifiers do not match, the files will be mapped separately. 
Then the alignments for each file are compared and if at least a cutoff fraction of the reads
can be considered concordant, the results.relationship is changed to "split_mates".

Note that this implementation is completely written in Python and will easily become the bottleneck
of the program as the logic by which the mappings are compared is all-vs-all for the two mates, so
if a high fraction of reads are multi-mapping, the execution will get significantly slower

Fixes #85 

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [x] I have performed a self-review of my own code
- [x] My code follows the existing coding style, lints and generates no new
      warnings
- [x] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [x] I have commented my code in hard-to-understand areas
- [x] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [x] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [x] I have updated any sections of the app's documentation that are affected
      by the proposed changes

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

2023-05-24 22:33 UTC, uniqueg requested changes
This looks pretty good to me, at first glance. I can't review in depth as it's getting late and I have an early and long flight tomorrow.

@balajtimate: could you help review and test this, please?

2023-05-24 22:33 UTC, uniqueg commented on htsinfer/cli.py
> +        )
Maybe add here that these are only used when the lib type cannot be inferred by regex from the seq identifiers

2023-05-24 22:33 UTC, uniqueg commented on README.md
> +			(default: 0.95)
Formatting seeems a little different than some other options (position and overall presence of `.` and the indentation.

However, I don't really care, as I think this should be removed from the `README.md` anyways. Not good to have this in too many places (docs, CLI args, models)...

2023-05-25 10:16 UTC, balajtimate commented
Sure, I'll run some tests and get back to it soon

2023-06-02 09:51 UTC, balajtimate reviewed
I ran the tests on our sample list of 385 PE samples, and when changing the seq IDs so that the pairs don't match, this seemed to correctly identify the "split_mates" relationships. 

However, when running it on some unrelated samples, and the lib type cannot be determined (both are NoneType), I seem to get a TypeError in the `_compare_alignments` function in `get_library_type.py`. I think the error occurs during the comparision of the separate mappings. You could recreate it by running HTSinfer on the `unmapped_paired_mate_1.fastq` and `second_mate.fastq` test files. Could you look into this?

2023-06-02 09:55 UTC, BorisYourich commented
Sure, thanks for taking the time, I will fix that soon as possible.

2023-06-02 10:41 UTC, BorisYourich commented
The issue was that I didn't consider reads that do not map at all, there is no need to include such alignments, therefore I added a check.

2023-06-02 11:11 UTC, balajtimate approved these changes, later dismissed
Perfect, it works great, thank you! I think if you make the changes Alex requested, it can be merged.

2023-06-02 11:24 UTC, BorisYourich commented
Okay, I just pushed the changes that Alex recommended, I think you can merge this.

2023-06-12 20:36 UTC, uniqueg approved these changes
Awesome job - thanks @BorisYourich and @balajtimate

2023-06-12 20:36 UTC, merged