feat: output read orientation fractions to json
zavolanlab/htsinfer pull request #169
Opened 2024-10-08 08:23 UTC by balajtimate

### Description

- Add json output of the fractions of read orientation (number of mapped reads, fraction of SF, SR and final orientation) per input sample
- Clean up debug logging

### Type of change

- [X] New feature (non-breaking change which adds functionality)

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [X] I have performed a self-review of my own code
- [X] My code follows the existing coding style, lints and generates no new
      warnings
- [X] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [X] I have commented my code in hard-to-understand areas
- [X] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [X] I have added tests that prove my fix is effective or that my feature
      works
- [X] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [X] I have updated any sections of the app's documentation that are affected
      by the proposed changes

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

2024-10-08 14:17 UTC, uniqueg requested changes
Some minor issues. In addition to the ones mentioned in line, I'm wondering if there aren't some docs that need to be updated? Example outputs maybe?

2024-10-08 14:17 UTC, uniqueg commented on htsinfer/get_read_orientation.py
> +        LOGGER.debug(f"Orientation: {orient_df.iloc[0, 3]}")
I still think these kinda messages aren't really debug level, they are very informative for the user (despite being in the output), so I think `INFO` would be much better suited here. If people would like to see only warnings, they can change the verbosity accordingly.

That being said, if the same principle is followed for other functionalities, i.e., that results/info messages are treated as debug it's not a matter for _this_ PR, but a separate one, that changes log levels for these kinda messages across all functionialities.

However, if it's only this one, please change here.

2024-10-08 14:17 UTC, uniqueg commented on htsinfer/get_read_orientation.py
> +        )
Why not call `create_orient_df()` here, since you already defined it (like you do for paired reads)?

2024-10-08 14:17 UTC, uniqueg commented on htsinfer/get_read_orientation.py
> +            self,
Do you really need `self` here? Seems like you don't, so I guess you should make it a `@staticmethod`.

2024-10-08 14:35 UTC, balajtimate commented on htsinfer/get_read_orientation.py
> +        LOGGER.debug(f"Orientation: {orient_df.iloc[0, 3]}")
Yes, they're all `DEBUG` for all other modules. I'll change them in another PR then.

2024-10-08 14:44 UTC, balajtimate commented on htsinfer/get_read_orientation.py
> +        )
Oops, I missed that, fixed that in the commit

2024-10-08 16:18 UTC, balajtimate commented
No docs update needed right now. I'll rewrite the full documentation on RtD, there it will be included.

2024-10-09 06:59 UTC, uniqueg commented
> No docs update needed right now. I'll rewrite the full documentation on RtD, there it will be included.

Oh, never mind. Had only a brief look and thought that you'd ended up including the stats in the main output after all. But seeing now that you're just writing it into a separate file, as discussed 👍

2024-10-09 06:59 UTC, uniqueg approved these changes

2024-10-09 06:59 UTC, merged